[tool.poetry]
name = "sensortrack"
version = "0.4.1"
description = "Historically track sensor data from SmartThings"
authors = ["Kenneth J. Pronovici <pronovic@ieee.org>"]
license = "Apache-2.0"
homepage = "https://github.com/pronovic/smartapp-sensortrack"
repository = "https://github.com/pronovic/smartapp-sensortrack"
include = [
   { path = 'Changelog', format = 'sdist' },
   { path = 'LICENSE', format = 'sdist' },
   { path = 'README.md', format = 'sdist' },
   { path = 'docs', format = 'sdist' },
   { path = 'tests', format = 'sdist' },
]
packages = [ 
   { include = "sensortrack", from = "src" },
]
classifiers=[
   "Programming Language :: Python :: 3",
   "License :: OSI Approved :: Apache Software License",
   "Operating System :: Unix",
   "Environment :: Console",
   "Environment :: No Input/Output (Daemon)",
   "Intended Audience :: Developers",
   "Natural Language :: English",
   "Topic :: Home Automation",
]

[tool.poetry.dependencies]
python = ">=3.9,<4"
fastapi = "^0.78.0"
uvicorn = "^0.17.6"
influxdb-client = "^1.29.1"
python-dotenv = "^0.20.0"
smartapp-sdk = "^0.5.0"
jsonpath-ng = "^1.5.3"
pytemperature = "^1.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-testdox = "^3.0.1"
coverage = "^6.3.2"
tox = "^3.25.0"
pylint = "~2.12"  # versions after 2.12 get into an infinite loop on Windows
toml = "^0.10.2"
pre-commit = "^2.18.1"
black = "^22.3.0"
mypy = "^0.950"
isort = "^5.10.1"
coveralls = "^3.3.1"
types-PyYAML = "^6.0.8"
pytest-asyncio = "^0.18.3"
types-requests = "^2.27.30"

[tool.black]
line-length = 132
target-version = ['py39', 'py310' ]
include = '(src\/scripts\/.*$|\.pyi?$)'
exclude = '''
/(
    \.git
  | __pycache__
  | \.tox
  | \.venv
  | build
  | dist
  | docs
  | notes
)/
'''

[tool.isort]
profile = "black"
line_length = 132
skip_glob = [ "docs", "notes" ]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
