apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    editable: true
    secureJsonData:
      token: admintoken
    jsonData:
      version: Flux
      organization: iot
      defaultBucket: metrics
      tlsSkipVerify: true
      timeInterval: 1m
